##############################################################################
# Copyright (c) 2019 opnfv.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
version: '3'
services:
    mongodb:
        image: mongo:3.2.1
        container_name: lfn-db
        volumes:
            - lfn-db:/data/db
        expose:
            - "27017"
    webopnfv:
        image: opnfv/dovetail-webportal-web:latest
        container_name: web-opnfv
        restart: always
        env_file:
            - config.env
            - vhost-opnfv.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - lfnapi
        ports:
            - "8080:8000"
    webonap:
        image: opnfv/dovetail-webportal-web-onap:latest
        container_name: web-onap
        restart: always
        env_file:
            - config.env
            - vhost-onap.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - lfnapi
        ports:
            - "8081:8000"
    lfnapi:
        image: opnfv/dovetail-webportal-api:latest
        container_name: lfn-api
        env_file:
            - config.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
            - lfn-company-logos:/home/testapi/media/companies
        ports:
            - "8082:8010"
    nginx:
        image: jwilder/nginx-proxy
        container_name: lfn-nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx-proxy/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
        depends_on:
            - webopnfv
            - webonap
        ports:
            - "80:80"

volumes:
    lfn-db:
    lfn-company-logos:
    lfn-testapi-logs:
