#######################################################
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
#

FROM ubuntu:16.04
MAINTAINER Leo Wang <grakiss.wanglei@huawei.com>
LABEL version="v2" description="OVP nginx"

ARG BRANCH=master

ENV HOME /home
WORKDIR $HOME

# Packaged dependencies
RUN apt-get update && apt-get install -y \
    git \
    nginx \
    supervisor \
    npm \
 && rm -rf /var/lib/apt/lists/*

RUN git config --global http.sslVerify false && \
    git clone https://gerrit.opnfv.org/gerrit/dovetail-webportal $HOME/testapi && \
    cd $HOME/testapi && \
    git checkout -f $BRANCH && \
    cd $HOME/testapi/3rd_party/static/testapi-ui && \
    npm install && \
    mkdir /www && \
    cp -r $HOME/testapi/3rd_party/static /www/

ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/sites-enabled/default /etc/nginx/sites-available/default
ADD nginx/sites-enabled/default /etc/nginx/sites-enabled/default
ADD supervisor/conf.d/nginx.conf /etc/supervisor/conf.d/nginx.conf
ADD start-nginx.sh $HOME/start-nginx.sh

CMD ["bash", "start-nginx.sh"]
