---
version: '3'
services:
    mongodb:
        image: mongo:3.2.1
        container_name: lfn-db
        volumes:
            - lfn-db:/data/db
        expose:
            - "27017"
    webopnfv:
        image: opnfv/dovetail-webportal-web:latest
        container_name: web-opnfv
        restart: always
        env_file:
            - config.env
            - vhost-opnfv.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - lfnapi
        ports:
            - "8000:8000"
    webonap:
        image: opnfv/dovetail-webportal-web-onap:latest
        container_name: web-onap
        restart: always
        env_file:
            - config.env
            - vhost-onap.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - lfnapi
        ports:
            - "8001:8000"
    weblfn:
        image: opnfv/dovetail-webportal-web-lfn:latest
        container_name: web-lfn
        restart: always
        env_file:
            - config.env
            - vhost-lfn.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - lfnapi
        ports:
            - "8002:8000"
    lfnapi:
        image: opnfv/dovetail-webportal-api:latest
        container_name: lfn-api
        env_file:
            - config.env
        volumes:
            - lfn-testapi-logs:/home/testapi/logs
            - lfn-company-logos:/home/testapi/media/companies
        ports:
            - "8010:8010"
    nginx:
        image: jwilder/nginx-proxy
        container_name: lfn-nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx-proxy/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
        depends_on:
            - webopnfv
            - webonap
            - weblfn
        ports:
            - "80:80"

volumes:
    lfn-db:
    lfn-company-logos:
    lfn-testapi-logs:
