---
version: '3'
services:
    testapi:
        image: opnfv/testapi:cvp.0.5.0
        container_name: cvp-testapi
        env_file:
            - config.env
        volumes:
            - cvp-testapi-logs:/home/testapi/logs
        links:
            - mongodb
        ports:
            - "8010:8010"
    mongodb:
        image: mongo:3.2.1
        container_name: cvp-db
        volumes:
            - cvp-db:/data/db
        expose:
            - "27017"
    web:
        image: opnfv/dovetail-webportal-web:latest
        container_name: cvp-web
        restart: always
        env_file:
            - config.env
            - vhost.env
        volumes:
            - cvp-testapi-logs:/home/testapi/logs
        links:
            - mongodb
            - testapi
            - cvpapi
        ports:
            - "8000:8000"
    cvpapi:
        image: opnfv/dovetail-webportal-api:latest
        container_name: cvp-cvpapi
        env_file:
            - config.env
        volumes:
            - cvp-testapi-logs:/home/testapi/logs
            - cvp-company-logos:/home/testapi/media/companies
        ports:
            - "8011:8011"
    nginx:
        image: jwilder/nginx-proxy
        container_name: cvp-nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx-proxy/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
        depends_on:
            - web
        ports:
            - "80:80"

volumes:
    cvp-db:
    cvp-company-logos:
    cvp-testapi-logs:
